package com.entity;

public class ApplyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.apply_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer apply_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String house_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.apply_id
     *
     * @return the value of apply.apply_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getApply_id() {
        return apply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.apply_id
     *
     * @param apply_id the value for apply.apply_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setApply_id(Integer apply_id) {
        this.apply_id = apply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.house_id
     *
     * @return the value of apply.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getHouse_id() {
        return house_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.house_id
     *
     * @param house_id the value for apply.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setHouse_id(String house_id) {
        this.house_id = house_id;
    }
}