package com.entity;

public class Applyout {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applyout.aoid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer aoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applyout.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String house_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applyout.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applyout.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applyout.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applyout.aoid
     *
     * @return the value of applyout.aoid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getAoid() {
        return aoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applyout.aoid
     *
     * @param aoid the value for applyout.aoid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setAoid(Integer aoid) {
        this.aoid = aoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applyout.house_id
     *
     * @return the value of applyout.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getHouse_id() {
        return house_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applyout.house_id
     *
     * @param house_id the value for applyout.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setHouse_id(String house_id) {
        this.house_id = house_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applyout.address
     *
     * @return the value of applyout.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applyout.address
     *
     * @param address the value for applyout.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applyout.status
     *
     * @return the value of applyout.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applyout.status
     *
     * @param status the value for applyout.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applyout.user_id
     *
     * @return the value of applyout.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applyout.user_id
     *
     * @param user_id the value for applyout.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}