package com.entity;

import java.util.Date;

public class Apply extends ApplyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.area
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Double area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.apply_date
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Date apply_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.address
     *
     * @return the value of apply.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.address
     *
     * @param address the value for apply.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.area
     *
     * @return the value of apply.area
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.area
     *
     * @param area the value for apply.area
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.price
     *
     * @return the value of apply.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.price
     *
     * @param price the value for apply.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.apply_date
     *
     * @return the value of apply.apply_date
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Date getApply_date() {
        return apply_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.apply_date
     *
     * @param apply_date the value for apply.apply_date
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setApply_date(Date apply_date) {
        this.apply_date = apply_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.status
     *
     * @return the value of apply.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.status
     *
     * @param status the value for apply.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.user_id
     *
     * @return the value of apply.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.user_id
     *
     * @param user_id the value for apply.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}