package com.entity;

public class Checkout {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.cid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String house_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.cid
     *
     * @return the value of checkout.cid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.cid
     *
     * @param cid the value for checkout.cid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.house_id
     *
     * @return the value of checkout.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getHouse_id() {
        return house_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.house_id
     *
     * @param house_id the value for checkout.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setHouse_id(String house_id) {
        this.house_id = house_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.address
     *
     * @return the value of checkout.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.address
     *
     * @param address the value for checkout.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.status
     *
     * @return the value of checkout.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.status
     *
     * @param status the value for checkout.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.user_id
     *
     * @return the value of checkout.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.user_id
     *
     * @param user_id the value for checkout.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}