package com.entity;

public class Hetong {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.chuzu
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String chuzu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.chuzu_idcard
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String chuzu_idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.zuke
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String zuke;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.zuke_idcard
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String zuke_idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.fromdate
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String fromdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.todate
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String todate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.area
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Double area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String house_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hetong.payday
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer payday;

    private int user_id;


    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.id
     *
     * @return the value of hetong.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.id
     *
     * @param id the value for hetong.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.chuzu
     *
     * @return the value of hetong.chuzu
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getChuzu() {
        return chuzu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.chuzu
     *
     * @param chuzu the value for hetong.chuzu
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setChuzu(String chuzu) {
        this.chuzu = chuzu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.chuzu_idcard
     *
     * @return the value of hetong.chuzu_idcard
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getChuzu_idcard() {
        return chuzu_idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.chuzu_idcard
     *
     * @param chuzu_idcard the value for hetong.chuzu_idcard
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setChuzu_idcard(String chuzu_idcard) {
        this.chuzu_idcard = chuzu_idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.zuke
     *
     * @return the value of hetong.zuke
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getZuke() {
        return zuke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.zuke
     *
     * @param zuke the value for hetong.zuke
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setZuke(String zuke) {
        this.zuke = zuke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.zuke_idcard
     *
     * @return the value of hetong.zuke_idcard
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getZuke_idcard() {
        return zuke_idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.zuke_idcard
     *
     * @param zuke_idcard the value for hetong.zuke_idcard
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setZuke_idcard(String zuke_idcard) {
        this.zuke_idcard = zuke_idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.fromdate
     *
     * @return the value of hetong.fromdate
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getFromdate() {
        return fromdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.fromdate
     *
     * @param fromdate the value for hetong.fromdate
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setFromdate(String fromdate) {
        this.fromdate = fromdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.todate
     *
     * @return the value of hetong.todate
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getTodate() {
        return todate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.todate
     *
     * @param todate the value for hetong.todate
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setTodate(String todate) {
        this.todate = todate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.price
     *
     * @return the value of hetong.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.price
     *
     * @param price the value for hetong.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.address
     *
     * @return the value of hetong.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.address
     *
     * @param address the value for hetong.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.area
     *
     * @return the value of hetong.area
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.area
     *
     * @param area the value for hetong.area
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.house_id
     *
     * @return the value of hetong.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getHouse_id() {
        return house_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.house_id
     *
     * @param house_id the value for hetong.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setHouse_id(String house_id) {
        this.house_id = house_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hetong.payday
     *
     * @return the value of hetong.payday
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getPayday() {
        return payday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hetong.payday
     *
     * @param payday the value for hetong.payday
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setPayday(Integer payday) {
        this.payday = payday;
    }
}