package com.entity;

public class Houselist extends HouselistKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houselist.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houselist.area
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Double area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houselist.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houselist.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houselist.address
     *
     * @return the value of houselist.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houselist.address
     *
     * @param address the value for houselist.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houselist.area
     *
     * @return the value of houselist.area
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houselist.area
     *
     * @param area the value for houselist.area
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houselist.price
     *
     * @return the value of houselist.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houselist.price
     *
     * @param price the value for houselist.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houselist.status
     *
     * @return the value of houselist.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houselist.status
     *
     * @param status the value for houselist.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }
}