package com.entity;

public class HouselistKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houselist.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houselist.houseid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String houseid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houselist.id
     *
     * @return the value of houselist.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houselist.id
     *
     * @param id the value for houselist.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houselist.houseid
     *
     * @return the value of houselist.houseid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getHouseid() {
        return houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houselist.houseid
     *
     * @param houseid the value for houselist.houseid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setHouseid(String houseid) {
        this.houseid = houseid;
    }
}