package com.entity;

public class Music {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.name
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.url
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.artist
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String artist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.cover
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String cover;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.name
     *
     * @return the value of music.name
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.name
     *
     * @param name the value for music.name
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.url
     *
     * @return the value of music.url
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.url
     *
     * @param url the value for music.url
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.artist
     *
     * @return the value of music.artist
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getArtist() {
        return artist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.artist
     *
     * @param artist the value for music.artist
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setArtist(String artist) {
        this.artist = artist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.cover
     *
     * @return the value of music.cover
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.cover
     *
     * @param cover the value for music.cover
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setCover(String cover) {
        this.cover = cover;
    }
}