package com.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Paid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paid.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paid.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String house_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paid.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paid.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paid.date
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paid.paydate
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    private Date paydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paid.name
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paid.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paid.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paid.id
     *
     * @return the value of paid.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paid.id
     *
     * @param id the value for paid.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paid.house_id
     *
     * @return the value of paid.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getHouse_id() {
        return house_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paid.house_id
     *
     * @param house_id the value for paid.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setHouse_id(String house_id) {
        this.house_id = house_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paid.address
     *
     * @return the value of paid.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paid.address
     *
     * @param address the value for paid.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paid.price
     *
     * @return the value of paid.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paid.price
     *
     * @param price the value for paid.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paid.date
     *
     * @return the value of paid.date
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paid.date
     *
     * @param date the value for paid.date
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paid.paydate
     *
     * @return the value of paid.paydate
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paid.paydate
     *
     * @param paydate the value for paid.paydate
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paid.name
     *
     * @return the value of paid.name
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paid.name
     *
     * @param name the value for paid.name
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paid.user_id
     *
     * @return the value of paid.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paid.user_id
     *
     * @param user_id the value for paid.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paid.status
     *
     * @return the value of paid.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paid.status
     *
     * @param status the value for paid.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }
}