package com.entity;

public class Schedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.date
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.content
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.id
     *
     * @return the value of schedule.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.id
     *
     * @param id the value for schedule.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.date
     *
     * @return the value of schedule.date
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.date
     *
     * @param date the value for schedule.date
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.content
     *
     * @return the value of schedule.content
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.content
     *
     * @param content the value for schedule.content
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setContent(String content) {
        this.content = content;
    }
}