package com.entity;

public class Userlist extends UserlistKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlist.name
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlist.phone
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlist.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlist.nickname
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String nickname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlist.name
     *
     * @return the value of userlist.name
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlist.name
     *
     * @param name the value for userlist.name
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlist.phone
     *
     * @return the value of userlist.phone
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlist.phone
     *
     * @param phone the value for userlist.phone
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlist.user_id
     *
     * @return the value of userlist.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlist.user_id
     *
     * @param user_id the value for userlist.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlist.nickname
     *
     * @return the value of userlist.nickname
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlist.nickname
     *
     * @param nickname the value for userlist.nickname
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
}