package com.entity;

public class UserlistKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlist.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlist.idcard
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String idcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlist.id
     *
     * @return the value of userlist.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlist.id
     *
     * @param id the value for userlist.id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlist.idcard
     *
     * @return the value of userlist.idcard
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlist.idcard
     *
     * @param idcard the value for userlist.idcard
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }
}