package com.entity;

public class Zulist extends ZulistKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zulist.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zulist.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zulist.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zulist.contract_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer contract_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zulist.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zulist.price
     *
     * @return the value of zulist.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zulist.price
     *
     * @param price the value for zulist.price
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zulist.address
     *
     * @return the value of zulist.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zulist.address
     *
     * @param address the value for zulist.address
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zulist.user_id
     *
     * @return the value of zulist.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zulist.user_id
     *
     * @param user_id the value for zulist.user_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zulist.contract_id
     *
     * @return the value of zulist.contract_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getContract_id() {
        return contract_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zulist.contract_id
     *
     * @param contract_id the value for zulist.contract_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setContract_id(Integer contract_id) {
        this.contract_id = contract_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zulist.status
     *
     * @return the value of zulist.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zulist.status
     *
     * @param status the value for zulist.status
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }
}