package com.entity;

public class ZulistKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zulist.zid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private Integer zid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zulist.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    private String house_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zulist.zid
     *
     * @return the value of zulist.zid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public Integer getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zulist.zid
     *
     * @param zid the value for zulist.zid
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setZid(Integer zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zulist.house_id
     *
     * @return the value of zulist.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public String getHouse_id() {
        return house_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zulist.house_id
     *
     * @param house_id the value for zulist.house_id
     *
     * @mbg.generated Wed Jul 19 18:49:40 CST 2023
     */
    public void setHouse_id(String house_id) {
        this.house_id = house_id;
    }
}