package com.mapper;

import com.entity.Apply;
import com.entity.Applyout;
import com.entity.Zulist;
import com.vo.ApplyBean;
import com.vo.SearchBean;

import java.util.List;

public interface ApplyoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(Integer aoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Applyout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Applyout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Applyout selectByPrimaryKey(Integer aoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Applyout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Applyout record);

    int insertByZulist(Zulist zulist);

    List<ApplyBean> findApplyOut(SearchBean searchBean);

    void deleteByHouseId(String id);

    Applyout findByHouseId(String house_id);
}