package com.mapper;

import com.entity.Apply;
import com.entity.ApplyKey;
import com.vo.ApplyBean;
import com.vo.SearchBean;

import java.util.List;

public interface ApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(ApplyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Apply selectByPrimaryKey(ApplyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Apply record);

    List<ApplyBean> findByUid(SearchBean searchBean);

    List<ApplyBean> findAll(SearchBean searchBean);

    void deleteByHouseId(String houseid);

    Apply findByHouseId(String house_id);
}