package com.mapper;

import com.entity.Apply;
import com.entity.Applyout;
import com.entity.Checkout;
import com.entity.Zulist;
import com.vo.SearchBean;

import java.util.List;

public interface CheckoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Checkout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Checkout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Checkout selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Checkout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Checkout record);

    List<Checkout> findCheckOut(SearchBean searchBean);

    void deleteByHouseId(String s);

    void insertByZulist(Zulist zulist);

    void insertByApply(Apply apply1);

    void insertByApplyout(Applyout applyout);
}