package com.mapper;

import com.entity.Apply;
import com.entity.Hetong;

public interface HetongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hetong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hetong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Hetong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hetong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Hetong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hetong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Hetong selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hetong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Hetong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hetong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Hetong record);

    Hetong findByContractId(Integer id);


    Hetong findByHouseId(String houseid);

    void deleteByHouseId(String id);

    void updateByHouseId(Hetong hetong);
}