package com.mapper;

import com.entity.Apply;
import com.entity.Houselist;
import com.entity.HouselistKey;
import com.vo.ApplyBean;
import com.vo.SearchBean;

import java.util.List;

public interface HouselistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houselist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(HouselistKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houselist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Houselist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houselist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Houselist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houselist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Houselist selectByPrimaryKey(HouselistKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houselist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Houselist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table houselist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Houselist record);

    List<Houselist> findAll(SearchBean searchBean);

    void updateStatus(Apply apply);

    Houselist findByAddress(Houselist house);

    Houselist findByHouseId(Houselist house);

    void deleteByHouseId(String s);
}