package com.mapper;

import com.entity.Music;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface MusicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Music record);

    @Select("select * from music")
    List<Music> findAll();
}