package com.mapper;

import com.entity.Paid;
import com.entity.Topaid;
import com.vo.SearchBean;

import java.util.List;

public interface PaidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Paid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Paid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Paid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Paid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Paid record);

    void insertByTopaid(Topaid topaid);

    void updateByHouseId(Paid paid);

    List<Paid> findAll(SearchBean searchBean);

    void deleteByHouseId(String s);
}