package com.mapper;

import com.entity.Solve;
import com.entity.Wrong;

import java.util.List;

public interface SolveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solve
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solve
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Solve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solve
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Solve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solve
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Solve selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solve
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Solve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solve
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Solve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solve
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Solve record);

    List<Solve> findByName(String name);

    void insertByWrong(Wrong wrong);
}