package com.mapper;

import com.entity.Topaid;
import com.vo.SearchBean;
import com.vo.ZulistBean;

import java.util.List;

public interface TopaidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topaid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topaid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Topaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topaid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Topaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topaid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Topaid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topaid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Topaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topaid
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Topaid record);

    List<Topaid> findByName(String name);

    void deleteByHouseId(String id);

    Topaid findByHouseId(String id);

    void updateByHouseId(Topaid topaid);

    List<ZulistBean> findAll(SearchBean searchBean);
}