package com.mapper;

import com.entity.Userlist;
import com.entity.UserlistKey;

public interface UserlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(UserlistKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Userlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Userlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Userlist selectByPrimaryKey(UserlistKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Userlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Userlist record);

    Userlist findByUid(Integer id);

    void updateByUid(Userlist userlist);
}