package com.mapper;

import com.entity.Solve;
import com.entity.Wrong;
import com.vo.SearchBean;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WrongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wrong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wrong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Wrong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wrong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Wrong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wrong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Wrong selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wrong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Wrong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wrong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Wrong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wrong
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Wrong record);

    List<Wrong> findByName(@Param("name") String name);

    List<Solve> findAll(SearchBean searchBean);
}