package com.mapper;

import com.entity.Hetong;
import com.entity.Zulist;
import com.entity.ZulistKey;
import com.vo.ApplyBean;
import com.vo.SearchBean;
import com.vo.ZulistBean;

import java.util.HashMap;
import java.util.List;

public interface ZulistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zulist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int deleteByPrimaryKey(ZulistKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zulist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insert(Zulist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zulist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int insertSelective(Zulist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zulist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    Zulist selectByPrimaryKey(ZulistKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zulist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKeySelective(Zulist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zulist
     *
     * @mbg.generated Sat Jul 15 15:05:57 CST 2023
     */
    int updateByPrimaryKey(Zulist record);

    List<ZulistBean> findAll(SearchBean searchBean);

    Zulist findByContractId(Integer id);

    void updateStatus(HashMap<String, Object> map);

    void insertByHetong(Hetong hetong1);

    void deleteByCid(Integer id);

    void deleteByHouseId(String id);
}